org:
  springframework:
    security:
      config:
        annotation:
          web:
            builders:
              WebSecurity:
                debugEnabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG